In [5]:
import os as os

In [8]:
os.chdir("C:\\Users\\litle\\OneDrive\\Desktop\\woking direectory")

In [9]:
os.listdir("C:\\Users\\litle\\OneDrive\\Desktop\\woking direectory")

['IRIS.csv',
 'iris.data',
 'Iris.xls',
 'mtcars.csv',
 'snsdata.csv',
 'Super Store.csv',
 'train.csv']

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
iris=pd.read_csv("iris.data")

In [12]:
iris.columns=["sepal_length","sepal_width","petal_length","petal_width","species"]

In [13]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   149 non-null    float64
 4   species       149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [14]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    149.000000   149.000000    149.000000   149.000000
mean       5.848322     3.051007      3.774497     1.205369
std        0.828594     0.433499      1.759651     0.761292
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [17]:
iris.shape

(149, 5)

In [18]:
iris=iris.iloc[:,0:4]

In [19]:
iris

sepal_length  sepal_width  petal_length  petal_width
0             4.9          3.0           1.4          0.2
1             4.7          3.2           1.3          0.2
2             4.6          3.1           1.5          0.2
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
144           6.7          3.0           5.2          2.3
145           6.3          2.5           5.0          1.9
146           6.5          3.0           5.2          2.0
147           6.2          3.4           5.4          2.3
148           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

In [20]:
#STANDARDISING THE DATASET
from sklearn.preprocessing import StandardScaler

In [22]:
iris_std=StandardScaler().fit_transform(iris)

In [23]:
iris_std

array([[-1.1483555 , -0.11805969, -1.35396443, -1.32506301],
       [-1.3905423 ,  0.34485856, -1.41098555, -1.32506301],
       [-1.51163569,  0.11339944, -1.29694332, -1.32506301],
       [-1.02726211,  1.27069504, -1.35396443, -1.32506301],
       [-0.54288852,  1.9650724 , -1.18290109, -1.0614657 ],
       [-1.51163569,  0.8077768 , -1.35396443, -1.19326436],
       [-1.02726211,  0.8077768 , -1.29694332, -1.32506301],
       [-1.75382249, -0.34951881, -1.35396443, -1.32506301],
       [-1.1483555 ,  0.11339944, -1.29694332, -1.45686167],
       [-0.54288852,  1.50215416, -1.29694332, -1.32506301],
       [-1.2694489 ,  0.8077768 , -1.23992221, -1.32506301],
       [-1.2694489 , -0.11805969, -1.35396443, -1.45686167],
       [-1.87491588, -0.11805969, -1.52502777, -1.45686167],
       [-0.05851493,  2.19653152, -1.46800666, -1.32506301],
       [-0.17960833,  3.122368  , -1.29694332, -1.0614657 ],
       [-0.54288852,  1.9650724 , -1.41098555, -1.0614657 ],
       [-0.90616871,  1.

In [24]:
#CALCULATE THE COVARIENCE MATRIX
iris_cov_matrix=np.cov(iris_std.T)

In [25]:
iris_cov_matrix

array([[ 1.00675676, -0.10448539,  0.87716999,  0.82249094],
       [-0.10448539,  1.00675676, -0.41802325, -0.35310295],
       [ 0.87716999, -0.41802325,  1.00675676,  0.96881642],
       [ 0.82249094, -0.35310295,  0.96881642,  1.00675676]])

In [27]:
eig_values,eig_vectors=np.linalg.eig(iris_cov_matrix)

In [28]:
print(eig_vectors)

[[ 0.52308496 -0.36956962 -0.72154279  0.26301409]
 [-0.25956935 -0.92681168  0.2411952  -0.12437342]
 [ 0.58184289 -0.01912775  0.13962963 -0.80099722]
 [ 0.56609604 -0.06381646  0.63380158  0.52321917]]


In [29]:
print(eig_values)

[2.92442837 0.93215233 0.14946373 0.02098259]


In [30]:
#MAKING A LIST OF EIGEN VECTORS AND CORRESPONDENT EIGEN VALUES
eig_pairs=[(np.abs(eig_values[i]),eig_vectors[:,i]) for i in range(len[])

SyntaxError: invalid syntax (<ipython-input-30-cf7417e8559c>, line 2)